kind: Deployment
apiVersion: apps/v1
metadata:
  name: frontend-client
spec:
  selector:
    matchLabels:
      app: frontend-client
  template:
    metadata:
      labels:
        app: frontend-client
    spec:
      containers:
        - name: frontend-client
          image: viniths/frontend:2.0
          ports:
            - containerPort: 80
          env:
            - name: REACT_APP_API_URL1
              value: http://127.0.0.1:57277
            - name: REACT_APP_API_URL2
              value: http://backend-server.default.svc.cluster.local:8001
            - name: REACT_APP_API_URL3
              value: http://127.0.0.1:59456

---

kind: Service
apiVersion: v1
metadata:
  name: frontend-client
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      nodePort: 31001
  selector:
    app: frontend-client
