apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-server-3
  labels:
    app: backend3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend3
  template:
    metadata:
      labels:
        app: backend3
    spec:
      containers:
        - name: backend3
          image: viniths/category:1.0
          ports:
            - containerPort: 8003
          env:
            - name: MONGO_URI
              value: mongodb://mongo:27017/ecommerce
            - name: BRAINTREE_MERCHANT_ID
              value: n74dc2kw9g3ws389
            - name: BRAINTREE_PUBLIC_KEY
              value: bgytmgzhz5f6t2tg
            - name: BRAINTREE_PRIVATE_KEY
              value: e6f226166da99d874f00008f0bba14f
