apiVersion: v1
kind: Service
metadata:
  name: backend-server-3
spec:
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 8003
      targetPort: 8003
  selector:
    app: backend3
