apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-server-2
  labels:
    app: backend2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend2
  template:
    metadata:
      labels:
        app: backend2
    spec:
      containers:
        - name: backend2
          image: viniths/order:1.0
          ports:
            - containerPort: 8002
          env:
            - name: MONGO_URI
              value: mongodb://mongo:27017/ecommerce
            - name: BRAINTREE_MERCHANT_ID
              value: n74dc2kw9g3ws389
            - name: BRAINTREE_PUBLIC_KEY
              value: bgytmgzhz5f6t2tg
            - name: BRAINTREE_PRIVATE_KEY
              value: e6f226166da99d874f00008f0bba14f
