apiVersion: v1
kind: Service
metadata:
  name: backend-server-2
spec:
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 8002
      targetPort: 8002
  selector:
    app: backend2
