apiVersion: v1
kind: Service
metadata:
  name: backend-server
spec:
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 8001
      targetPort: 8001
  selector:
    app: backend
